id: P6E64FB26
initial_creation_type: ocr
source_metadata:
  volumes:
    d6fddb653b0d4f08a5ccaf2c403cc99e:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: ཀྱེའི་རྡོ་རྗེ་ལས་བྱུང་བའི་ཀུ་རུ་ཀུ་ལླེའི་མན་ངག་ཆེན་པོ་ལྔ།
      total_pages: 2069
      volume_number: 5
